---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: send-uploads-v1
  namespace: default
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
