---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Brussels
  METALLB_LB_RANGE: 10.48.110.220-10.48.110.230
  METALLB_K8S_GATEWAY_ADDR: 10.48.110.220
  METALLB_INGRESS_ADDR: 10.48.110.221
