---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - helm-release.yaml
  - certificate.yaml
configMapGenerator:
  - name: proxied-networks
    files:
      - proxied-networks.txt
generatorOptions:
  disableNameSuffixHash: true
