---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system
  - cert-manger
  - default
  - home
  - flux-system
  - kube-system
  - monitoring
  - networking
  - system-upgrade
