# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:r6JIknag2DJzGNyD6IRd+HCGsy7OQxOT1m9ngm5bJooVpsXg7w==,iv:hG+icD1YLfKVlEwxfrni7uQKfyhUlYgQUH8L1hb3KDU=,tag:gS50yA6asYivREMd404gOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeWo5L2ZnTmorVVY4SUdP
            Q0QrRzVsWXRwNFVMWHBKSHNvOUVWRm9rT0NBClpjQy9vTHk1RFRNN2hNTjV0RDNI
            RVpucWVBcU5mUTR0aVE5Vm5ibmlpRFEKLS0tIERGVDdNTkh1dHFYR3ZtekRCUzJK
            ejg5dkpGczdUVGRXbFFRQ2hQUEQzYjgKcSzo7ZhElLPFs1GOZwXF8QLD9ih/ckBB
            oUBRSARrt14wDDWvUty5serRtM9QMwvAzbjslDlyWL6fuux/2I6BxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-23T22:32:53Z"
    mac: ENC[AES256_GCM,data:iCUq6yizxShH0sj4RQGeOo64gIlUObm3Ow8BMGbVD1PJGwaYIKg6qCChQ6tXgWC8/EconjWyf9cYbDiPufLt+Dv/O6gqWO3dOQOPKk1yDC61DFZNuWrOIZAIER1VUHSeSKmhM21gNos4Gu39CGoJyRLnSYFPJpuSh+c/eGv7m0k=,iv:qRkoCz2TbahX/X8D/rIrO75gD/66QWt42/1EccKaSEY=,tag:FX+t9aEJZaO9/eBvFO6mzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
