---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: send
  namespace: home
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: send
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: rook-ceph
      namespace: rook-ceph

  values:
    env:
      TZ: "${TIMEZONE}"
      BASE_URL: "send.${SECRET_DOMAIN}"
      DETECT_BASE_URL: true

    persistence:
      uploads:
        enabled: true
        existingClaim: send-uploads-v1

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "send"
        hosts:
          - host: &host "{{ .release.name }}.${secret_domain}"
            paths:
              - path: /
                pathtype: prefix

          - host: &suprise "suprise.${secret_domain}"
            paths:
              - path: /
                pathtype: prefix
        tls:
          - hosts:
              - *host
              - *suprise
            secretName: "send-tls"
