---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: send
  namespace: home
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: send
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: rook-ceph
      namespace: rook-ceph

  values:
    initContainers:
      init-permission:
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
        args:
          - chown 1000:1000 /uploads;
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: uploads
            mountPath: /uploads

    env:
      TZ: "${TIMEZONE}"
      BASE_URL: "send.${SECRET_DOMAIN}"
      DETECT_BASE_URL: true
      FILE_DIR: "/uploads"

    persistence:
      uploads:
        enabled: true
        existingClaim: send-uploads-v1

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "send"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathtype: prefix
          - host: &suprise "suprise.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathtype: prefix
        tls:
          - hosts:
              - *host
              - *suprise
            secretName: "send-tls"
