---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: send-uploads-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
