# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-notification-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bU5HS2yYjLKGYl7SZCuSfiK6hd3XYkMBs8VsrcC6oIFhmzC77NlyDQ==,iv:ODC0ZdFU9dODrFiPTZN3kPcQgQ3tCs69/SUmvw62Up8=,tag:TeYx1cM1Geuj8XXCPKoTqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8k6aj5un65mwy7t0s6sndrpqevp3hr749facgl3ha8w5dsxqp7s95phh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ditsUUN2RE5DWWs3bk9k
            bmQ5ZEM0MXN2YTlDdWVTTG5uZy9vZ2xPL1VrCkIyUnpRSGxmeU45dGxHYmg2bmd0
            SDE0NW5FenQ3Z2RhckR0a0JaWEp0MVEKLS0tIEZrdlZqMHZpT1VUVURZUnNRaU8y
            RmU2c25tdjZZNUZNM2Jnd0NReXRWVkkKBqu8uO8cNEP7PQHtIwTFBqzjZSJMBfnj
            dO0zriLQsOQOxpC8PTOu0pjIZQN0q1d+t/89HtcrTNdq7dkhjFw7dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-23T14:32:46Z"
    mac: ENC[AES256_GCM,data:mnifcx1owLEY6fxnw7c1Jm5y8EHPLJJBiA3kSkJL3LrqIA4ZcXfXwyTRw7JOeAXS0grBSKKHmHaRwQ5MIDSijybmqa99EuqMXSYvGxtUN/VmJerTBLamPa27Se63MSXUrqAzVUKdjL2VYoFZ7YSjDJNW2QLu6zQzknwWv1/oE5Y=,iv:Jh51SJvfyTnP5KarQGDiMw0cby8Odxleo/1FHLEU/oE=,tag:yvq4L7ellb/Krg7d/E/Zkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
